#!/bin/bash

set -e

DEVICE=$1
if [ -z "$DEVICE" ];then
    echo "No device given"
    exit 1
fi

grep -v GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub > /tmp/grub
mv /tmp/grub /target/etc/default/grub
cat << @@EOF >> /target/etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="rw quiet console=tty2"
@@EOF

/bin/mount --bind /dev /target/dev
/bin/mount --bind /proc /target/proc
/bin/mount --bind /sys /target/sys
/usr/sbin/grub-install --recheck --root-directory=/target $DEVICE
sudo chroot /target /usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg 
/bin/umount /target/dev
/bin/umount /target/proc
/bin/umount /target/sys
