#!/bin/bash

set -e

/bin/umount /target/dev/pts
/bin/umount /target/dev
/bin/umount /target/proc

/bin/umount --recursive /target/sys

## check if there is mounted-separated home partition. if true, unmount
if cat /proc/mounts | grep -F " /target/home " > /dev/null; then
  /bin/umount /target/home
fi

/bin/umount /target
rm -rf /rofs
