#!/bin/bash

# This secure-post-install script will reconfigure the system with real values from post installation step

export PATH=$PATH:/usr/sbin:/usr/bin:/bin:/sbin

read PASSPHRASE ROOTPASSWORD HOSTNAME FULLNAME USERNAME PASSWORD < /postinstall/config
echo -n $PASSPHRASE > /postinstall/config-passphrase
RANDOMPASS=`cat /postinstall/pass`
RANDOMUSERNAME=`cat /postinstall/user-pass | cut -d':' -f1`

set -e

###### REMOVE PACKAGES
echo "Remove packages"
/usr/bin/apt-get --yes purge blankon-installer blankon-repository-setup
echo "Removing unused dependencies"
/usr/bin/apt-get --yes autoremove

###### ENCRYPTION SPECIFIC SETTING UP
echo "Encryption specific setting up"

# Add new luks key
echo -n $RANDOMPASS | cryptsetup luksAddKey /dev/lvm/root /postinstall/config-passphrase
echo -n $RANDOMPASS | cryptsetup luksRemoveKey /dev/lvm/root
# Remove askpass bypass from the cryproot hook file
sed -i 's/cp -a \/tmp\/askpass \$DESTDIR\/lib\/cryptsetup\/askpass//' /etc/initramfs-tools/hooks/cryptroot

###### HOSTNAME
echo "Setting up hostname $HOSTNAME"
echo $HOSTNAME >  /etc/hostname
    cat << @@EOF > /etc/hosts 
127.0.0.1   localhost $HOSTNAME

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
@@EOF

###### USER
echo "Configuring user $USERNAME"

# This is the original group used in full ISO of BlankOn, since the current ISO generate the minimum packages,
# some groups doesnt exist.
# USER_GROUPS=sudo,cdrom,floppy,audio,dip,video,plugdev,scanner,netdev,bluetooth

USER_GROUPS=sudo,cdrom,floppy,audio,dip,video,plugdev,netdev
/usr/sbin/useradd -G $USER_GROUPS -m -s /bin/bash $USERNAME
echo "$USERNAME:$PASSWORD" | /usr/sbin/chpasswd $USERNAME
#/usr/bin/chfn < $ROOTFS/tmp/user-info
echo "root:$ROOTPASSWORD" | /usr/sbin/chpasswd root

/usr/sbin/userdel -rf $RANDOMUSERNAME

###### CUSTOM GROUP

#if [ -n "$BI_CUSTOM_GROUPS" ];then
#  for i in $BI_CUSTOM_GROUPS;do
#    do_chroot /usr/sbin/groupadd -r $i
#    do_chroot /usr/sbin/adduser $USERNAME $i
#  done
#fi

###### DISABLE AUTOLOGIN
echo "Disable autologin"
sed -i -r -e "s/autologin-/#autologin-/g" /usr/share/lightdm/lightdm.conf.d/40-lightdm-webkit-greeter.conf

###### Accounts service
echo "Account service"
if [ -f /run/accounts-service ];then
  cp /run/accounts-service /var/lib/AccountsService/users/$USERNAME
fi
    
##### UPDATE INITRAMFS
echo "Update initramfs"
CRYPTSETUP=y /usr/sbin/update-initramfs -u -k all

##### REMOVE POST INSTALLATION FILE
#echo "Remove post install files"
rm -rf /postinstall
