#!/bin/bash

set -e

rm -rf /rofs
mkdir /rofs
mount -o loop /lib/live/mount/medium/live/filesystem.squashfs /rofs
cp -a /rofs/* /target
cp -a /usr/lib/locale/locale-archive /target/usr/lib/locale/
umount /rofs
