#!/bin/bash

set -e

mkdir /rofs
mount -o loop /lib/live/mount/medium/live/filesystem.squashfs /rofs
rsync -av --progress /rofs/* /target > /tmp/b-i-copy-fs-progress
cp -a /usr/lib/locale/locale-archive /target/usr/lib/locale/
umount /rofs
