#!/bin/bash

set -e

PATH=$PATH:/usr/sbin

###### REMOVE PACKAGES

P=""
if [ -f /live/image/live/packages-to-remove ];then
    for i in `cat /live/image/live/packages-to-remove`;do
        P="$P $i"
    done
fi

if [ "x$P" != "x" ];then
    chroot /target /usr/bin/apt-get --yes purge $P
fi

chroot /target /usr/sbin/update-initramfs -k all -u
chroot /target /usr/bin/apt-get --yes autoremove

###### USER

read USERNAME FULLNAME < /tmp/user-setup
rm -f /tmp/user-setup
chroot /target /usr/sbin/useradd -c "$FULLNAME" -m $USERNAME -s /bin/bash

chroot /target /usr/sbin/chpasswd < /tmp/user-pass
rm -f /target/tmp/user-pass

###### HOSTNAME

read HOSTNAME < /tmp/hostname
mv /tmp/hostname /target/etc/
    cat << @@EOF > /target/etc/hosts 
127.0.0.1   localhost
127.0.1.1   $HOSTNAME

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
@@EOF

