#!/bin/bash

set -e

PATH=$PATH:/usr/sbin:/usr/bin

function do_chroot() {
    chroot /target /usr/bin/env PATH=$PATH $@ 
}

###### REMOVE PACKAGES

P=""
if [ -f /live/image/live/packages-to-remove ];then
    for i in `cat /live/image/live/packages-to-remove`;do
        P="$P $i"
    done
fi

if [ "x$P" != "x" ];then
    do_chroot /usr/bin/apt-get --yes purge $P
fi

do_chroot /usr/sbin/update-initramfs -k all -u
do_chroot /usr/bin/apt-get --yes autoremove
do_chroot /usr/bin/apt-get --yes clean 

###### USER

read AUTOLOGIN USERNAME FULLNAME < /tmp/user-setup
rm -f /tmp/user-setup
USER_GROUPS=sudo,cdrom,floppy,audio,dip,video,plugdev,scanner,netdev,bluetooth
do_chroot /usr/sbin/useradd -G $USER_GROUPS -c "$FULLNAME" -m $USERNAME -s /bin/bash

do_chroot /usr/sbin/chpasswd < /tmp/user-pass
rm -f /target/tmp/user-pass

###### AUTOLOGIN

if [ "x$AUTOLOGIN" = "x1" ];then
    if [ -s /target/var/lib/dpkg/info/lightdm.list ];then
        if [ -s /target/etc/lightdm/lightdm.conf ];then
            sed -i -r -e "s|^#.*autologin-user=.*\$|autologin-user=$USERNAME|" \
                      -e "s|^#.*autologin-user-timeout=.*\$|autologin-user-timeout=0|" \
                      /target/etc/lightdm/lightdm.conf
        fi
        if [ ! -s /target/etc/pam.d/lightdm-autologin ];then
            cat << @@EOF > /target/etc/pam.d/lightdm-autologin
auth requisite pam_nologin.so
auth required pam_env.so readenv=1
auth required pam_env.so readenv=1 envfile=/etc/default/locale
auth    required    pam_succeed_if.so user != root quiet_success
auth required pam_permit.so
@include common-account
session required pam_limits.so
@include common-session
@include common-password
@@EOF
        fi
    fi
fi
###### HOSTNAME

read HOSTNAME < /tmp/hostname
mv /tmp/hostname /target/etc/
    cat << @@EOF > /target/etc/hosts 
127.0.0.1   localhost $HOSTNAME

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
@@EOF


###### OpenSSH server
if [ -e /target/var/lib/dpkg/info/openssh-server.postinst ]; then
    if ! ls /target/etc/ssh/ssh_host_*_key > /dev/null 2>&1; then
        do_chroot /usr/sbin/dpkg-reconfigure --no-reload openssh-server
    fi
fi
