/* main.c generated by valac 0.26.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <locale.h>
#include <glib/gi18n-lib.h>
#include <config.h>
#include <gtk/gtk.h>
#include <webkit/webkit.h>
#include <gdk/gdk.h>


#define TYPE_INSTALLER (installer_get_type ())
#define INSTALLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INSTALLER, Installer))
#define INSTALLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_INSTALLER, InstallerClass))
#define IS_INSTALLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INSTALLER))
#define IS_INSTALLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_INSTALLER))
#define INSTALLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_INSTALLER, InstallerClass))

typedef struct _Installer Installer;
typedef struct _InstallerClass InstallerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



gint _vala_main (gchar** args, int args_length1);
GType installer_get_type (void) G_GNUC_CONST;
Installer* installer_new (void);
Installer* installer_construct (GType object_type);
void installer_start (Installer* self);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	GtkWindow* w = NULL;
	GtkWindow* _tmp0_ = NULL;
	Installer* i = NULL;
	Installer* _tmp1_ = NULL;
	GdkScreen* screen = NULL;
	GdkScreen* _tmp2_ = NULL;
	GdkScreen* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	setlocale (LC_ALL, "");
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
	gtk_init (&args_length1, &args);
	_tmp0_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
	g_object_ref_sink (_tmp0_);
	w = _tmp0_;
	_tmp1_ = installer_new ();
	g_object_ref_sink (_tmp1_);
	i = _tmp1_;
	gtk_container_add ((GtkContainer*) w, (GtkWidget*) i);
	gtk_widget_show_all ((GtkWidget*) w);
	gtk_window_fullscreen (w);
	gtk_window_move (w, 0, 0);
	_tmp2_ = gdk_screen_get_default ();
	_tmp3_ = _g_object_ref0 (_tmp2_);
	screen = _tmp3_;
	_tmp4_ = gdk_screen_width ();
	_tmp5_ = gdk_screen_height ();
	gtk_window_resize (w, _tmp4_, _tmp5_);
	installer_start (i);
	gtk_main ();
	result = 0;
	_g_object_unref0 (screen);
	_g_object_unref0 (i);
	_g_object_unref0 (w);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



