/* utils.c generated by valac 0.26.1, the Vala compiler
 * generated from utils.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>
#include <JavaScriptCore/JavaScript.h>
#include <gtk/gtk.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _JSStringRelease0(var) ((var == NULL) ? NULL : (var = (JSStringRelease (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_dir_close0(var) ((var == NULL) ? NULL : (var = (g_dir_close (var), NULL)))
#define _JSClassRelease0(var) ((var == NULL) ? NULL : (var = (JSClassRelease (var), NULL)))
#define _gtk_icon_info_free0(var) ((var == NULL) ? NULL : (var = (gtk_icon_info_free (var), NULL)))



void utils_write_simple_file (const gchar* path, const gchar* content);
void* utils_js_get_icon_path (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
gchar* utils_get_icon_path (const gchar* name, gint size);
void* utils_js_get_timezones (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _utils_js_get_icon_path_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
static void* _utils_js_get_timezones_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void utils_setup_js_class (void* context);

const JSStaticFunction UTILS_js_funcs[3] = {{"getIconPath", _utils_js_get_icon_path_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {"getTimezones", _utils_js_get_timezones_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {NULL, NULL, 0}};
const JSClassDefinition UTILS_js_class = {0, kJSClassAttributeNone, "Utils", NULL, NULL, UTILS_js_funcs, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};

void utils_write_simple_file (const gchar* path, const gchar* content) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (path != NULL);
	g_return_if_fail (content != NULL);
	{
		GFile* file = NULL;
		const gchar* _tmp0_ = NULL;
		GFile* _tmp1_ = NULL;
		GFile* _tmp2_ = NULL;
		gboolean _tmp3_ = FALSE;
		GFileOutputStream* _tmp5_ = NULL;
		GFile* _tmp6_ = NULL;
		GFileOutputStream* _tmp7_ = NULL;
		GDataOutputStream* dos = NULL;
		GDataOutputStream* _tmp8_ = NULL;
		GDataOutputStream* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		GDataOutputStream* _tmp11_ = NULL;
		_tmp0_ = path;
		_tmp1_ = g_file_new_for_path (_tmp0_);
		file = _tmp1_;
		_tmp2_ = file;
		_tmp3_ = g_file_query_exists (_tmp2_, NULL);
		if (_tmp3_) {
			GFile* _tmp4_ = NULL;
			_tmp4_ = file;
			g_file_delete (_tmp4_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_object_unref0 (file);
				goto __catch9_g_error;
			}
		}
		_tmp6_ = file;
		_tmp7_ = g_file_create (_tmp6_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
		_tmp5_ = _tmp7_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (file);
			goto __catch9_g_error;
		}
		_tmp8_ = g_data_output_stream_new ((GOutputStream*) _tmp5_);
		dos = _tmp8_;
		_tmp9_ = dos;
		_tmp10_ = content;
		g_data_output_stream_put_string (_tmp9_, _tmp10_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (dos);
			_g_object_unref0 (_tmp5_);
			_g_object_unref0 (file);
			goto __catch9_g_error;
		}
		_tmp11_ = dos;
		g_output_stream_close ((GOutputStream*) _tmp11_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (dos);
			_g_object_unref0 (_tmp5_);
			_g_object_unref0 (file);
			goto __catch9_g_error;
		}
		_g_object_unref0 (dos);
		_g_object_unref0 (_tmp5_);
		_g_object_unref0 (file);
	}
	goto __finally9;
	__catch9_g_error:
	{
		GError* e = NULL;
		FILE* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		GError* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp12_ = stderr;
		_tmp13_ = path;
		_tmp14_ = e;
		_tmp15_ = _tmp14_->message;
		fprintf (_tmp12_, "Error writing to %s: %s\n", _tmp13_, _tmp15_);
		_g_error_free0 (e);
	}
	__finally9:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


void* utils_js_get_icon_path (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp25_ = NULL;
	void* _tmp26_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 > 0) {
		void* s = NULL;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* _tmp2_ = NULL;
		void* _tmp3_ = NULL;
		void* _tmp4_ = NULL;
		gchar* buffer = NULL;
		void* _tmp5_ = NULL;
		gsize _tmp6_ = 0UL;
		gchar* _tmp7_ = NULL;
		gint buffer_length1 = 0;
		gint _buffer_size_ = 0;
		void* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		gchar* _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		gint size = 0;
		void** _tmp11_ = NULL;
		gint _tmp11__length1 = 0;
		gchar* _tmp17_ = NULL;
		gint _tmp17__length1 = 0;
		gint _tmp18_ = 0;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		void* _tmp21_ = NULL;
		void* _result_ = NULL;
		void* _tmp22_ = NULL;
		void* _tmp23_ = NULL;
		void* _tmp24_ = NULL;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		_tmp2_ = _tmp1_[0];
		_tmp3_ = ctx;
		_tmp4_ = JSValueToStringCopy (_tmp3_, _tmp2_, NULL);
		s = _tmp4_;
		_tmp5_ = s;
		_tmp6_ = JSStringGetLength (_tmp5_);
		_tmp7_ = g_new0 (gchar, _tmp6_ + 1);
		buffer = _tmp7_;
		buffer_length1 = _tmp6_ + 1;
		_buffer_size_ = buffer_length1;
		_tmp8_ = s;
		_tmp9_ = buffer;
		_tmp9__length1 = buffer_length1;
		_tmp10_ = buffer;
		_tmp10__length1 = buffer_length1;
		JSStringGetUTF8CString (_tmp8_, _tmp9_, (gsize) _tmp10__length1);
		size = 24;
		_tmp11_ = arguments;
		_tmp11__length1 = arguments_length1;
		if (_tmp11__length1 > 1) {
			gboolean size_d = FALSE;
			void** _tmp12_ = NULL;
			gint _tmp12__length1 = 0;
			void* _tmp13_ = NULL;
			void* _tmp14_ = NULL;
			gboolean _tmp15_ = FALSE;
			gboolean _tmp16_ = FALSE;
			_tmp12_ = arguments;
			_tmp12__length1 = arguments_length1;
			_tmp13_ = _tmp12_[1];
			_tmp14_ = ctx;
			_tmp15_ = JSValueToNumber (_tmp14_, _tmp13_, NULL);
			size_d = _tmp15_;
			_tmp16_ = size_d;
			size = (gint) _tmp16_;
		}
		_tmp17_ = buffer;
		_tmp17__length1 = buffer_length1;
		_tmp18_ = size;
		_tmp19_ = utils_get_icon_path ((const gchar*) _tmp17_, _tmp18_);
		_tmp20_ = _tmp19_;
		_tmp21_ = JSStringCreateWithUTF8CString (_tmp20_);
		_JSStringRelease0 (s);
		s = _tmp21_;
		_g_free0 (_tmp20_);
		_tmp22_ = ctx;
		_tmp23_ = s;
		_tmp24_ = JSValueMakeString (_tmp22_, _tmp23_);
		_result_ = _tmp24_;
		_JSStringRelease0 (s);
		s = NULL;
		buffer = (g_free (buffer), NULL);
		buffer = NULL;
		buffer_length1 = 0;
		_buffer_size_ = buffer_length1;
		result = _result_;
		buffer = (g_free (buffer), NULL);
		_JSStringRelease0 (s);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp25_ = ctx;
	_tmp26_ = JSValueMakeUndefined (_tmp25_);
	result = _tmp26_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


void* utils_js_get_timezones (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp45_ = NULL;
	void* _tmp46_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 > 0) {
		void* s = NULL;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* _tmp2_ = NULL;
		void* _tmp3_ = NULL;
		void* _tmp4_ = NULL;
		gchar* buffer = NULL;
		void* _tmp5_ = NULL;
		gsize _tmp6_ = 0UL;
		gchar* _tmp7_ = NULL;
		gint buffer_length1 = 0;
		gint _buffer_size_ = 0;
		void* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		gchar* _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		GString* json = NULL;
		GString* _tmp11_ = NULL;
		GString* _tmp12_ = NULL;
		GDir* dir = NULL;
		gchar* _tmp13_ = NULL;
		gint _tmp13__length1 = 0;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		GDir* _tmp16_ = NULL;
		GDir* _tmp17_ = NULL;
		FILE* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		gint _tmp19__length1 = 0;
		gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		GString* _tmp30_ = NULL;
		const gchar* _tmp31_ = NULL;
		GString* _tmp32_ = NULL;
		gssize _tmp33_ = 0L;
		gchar _tmp34_ = '\0';
		GString* _tmp38_ = NULL;
		GString* _tmp39_ = NULL;
		const gchar* _tmp40_ = NULL;
		void* _tmp41_ = NULL;
		void* r = NULL;
		void* _tmp42_ = NULL;
		void* _tmp43_ = NULL;
		void* _tmp44_ = NULL;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		_tmp2_ = _tmp1_[0];
		_tmp3_ = ctx;
		_tmp4_ = JSValueToStringCopy (_tmp3_, _tmp2_, NULL);
		s = _tmp4_;
		_tmp5_ = s;
		_tmp6_ = JSStringGetLength (_tmp5_);
		_tmp7_ = g_new0 (gchar, _tmp6_ + 1);
		buffer = _tmp7_;
		buffer_length1 = _tmp6_ + 1;
		_buffer_size_ = buffer_length1;
		_tmp8_ = s;
		_tmp9_ = buffer;
		_tmp9__length1 = buffer_length1;
		_tmp10_ = buffer;
		_tmp10__length1 = buffer_length1;
		JSStringGetUTF8CString (_tmp8_, _tmp9_, (gsize) _tmp10__length1);
		_tmp11_ = g_string_new ("");
		json = _tmp11_;
		_tmp12_ = json;
		g_string_assign (_tmp12_, "[");
		_tmp13_ = buffer;
		_tmp13__length1 = buffer_length1;
		_tmp14_ = g_strdup_printf ("/usr/share/zoneinfo/%s", (const gchar*) _tmp13_);
		_tmp15_ = _tmp14_;
		_tmp16_ = g_dir_open (_tmp15_, (guint) 0, &_inner_error_);
		_tmp17_ = _tmp16_;
		_g_free0 (_tmp15_);
		dir = _tmp17_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_string_free0 (json);
			buffer = (g_free (buffer), NULL);
			_JSStringRelease0 (s);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp18_ = stdout;
		_tmp19_ = buffer;
		_tmp19__length1 = buffer_length1;
		_tmp20_ = g_strconcat ("ldokqwpdkqwpdkw ", (const gchar*) _tmp19_, NULL);
		_tmp21_ = _tmp20_;
		fprintf (_tmp18_, "%s", _tmp21_);
		_g_free0 (_tmp21_);
		while (TRUE) {
			gchar* name = NULL;
			GDir* _tmp22_ = NULL;
			const gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
			const gchar* _tmp25_ = NULL;
			GString* _tmp26_ = NULL;
			const gchar* _tmp27_ = NULL;
			gchar* _tmp28_ = NULL;
			gchar* _tmp29_ = NULL;
			_tmp22_ = dir;
			_tmp23_ = g_dir_read_name (_tmp22_);
			_tmp24_ = g_strdup (_tmp23_);
			name = _tmp24_;
			_tmp25_ = name;
			if (_tmp25_ == NULL) {
				_g_free0 (name);
				break;
			}
			_tmp26_ = json;
			_tmp27_ = name;
			_tmp28_ = g_strdup_printf ("'%s',", _tmp27_);
			_tmp29_ = _tmp28_;
			g_string_append (_tmp26_, _tmp29_);
			_g_free0 (_tmp29_);
			_g_free0 (name);
		}
		_tmp30_ = json;
		_tmp31_ = _tmp30_->str;
		_tmp32_ = json;
		_tmp33_ = _tmp32_->len;
		_tmp34_ = string_get (_tmp31_, (glong) (_tmp33_ - 1));
		if (_tmp34_ == ',') {
			GString* _tmp35_ = NULL;
			GString* _tmp36_ = NULL;
			gssize _tmp37_ = 0L;
			_tmp35_ = json;
			_tmp36_ = json;
			_tmp37_ = _tmp36_->len;
			g_string_erase (_tmp35_, _tmp37_ - 1, (gssize) 1);
		}
		_tmp38_ = json;
		g_string_append (_tmp38_, "]");
		_tmp39_ = json;
		_tmp40_ = _tmp39_->str;
		_tmp41_ = JSStringCreateWithUTF8CString (_tmp40_);
		_JSStringRelease0 (s);
		s = _tmp41_;
		_tmp42_ = ctx;
		_tmp43_ = s;
		_tmp44_ = JSEvaluateScript (_tmp42_, _tmp43_, NULL, NULL, 0, NULL);
		r = _tmp44_;
		_JSStringRelease0 (s);
		s = NULL;
		buffer = (g_free (buffer), NULL);
		buffer = NULL;
		buffer_length1 = 0;
		_buffer_size_ = buffer_length1;
		result = r;
		_g_dir_close0 (dir);
		_g_string_free0 (json);
		buffer = (g_free (buffer), NULL);
		_JSStringRelease0 (s);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp45_ = ctx;
	_tmp46_ = JSValueMakeUndefined (_tmp45_);
	result = _tmp46_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static void* _utils_js_get_icon_path_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_get_icon_path (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _utils_js_get_timezones_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_get_timezones (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


void utils_setup_js_class (void* context) {
	void* c = NULL;
	void* _tmp0_ = NULL;
	void* o = NULL;
	void* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* g = NULL;
	void* _tmp4_ = NULL;
	void* _tmp5_ = NULL;
	void* s = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	g_return_if_fail (context != NULL);
	_tmp0_ = JSClassCreate (&UTILS_js_class);
	c = _tmp0_;
	_tmp1_ = context;
	_tmp2_ = context;
	_tmp3_ = JSObjectMake (_tmp1_, c, _tmp2_);
	o = _tmp3_;
	_tmp4_ = context;
	_tmp5_ = JSContextGetGlobalObject (_tmp4_);
	g = _tmp5_;
	_tmp6_ = JSStringCreateWithUTF8CString ("Utils");
	s = _tmp6_;
	_tmp7_ = context;
	JSObjectSetProperty (_tmp7_, g, s, o, kJSPropertyAttributeNone, NULL);
	_JSStringRelease0 (s);
	_0 (g);
	_0 (o);
	_JSClassRelease0 (c);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gchar* utils_get_icon_path (const gchar* name, gint size) {
	gchar* result = NULL;
	GtkIconTheme* icon = NULL;
	GtkIconTheme* _tmp0_ = NULL;
	GtkIconTheme* _tmp1_ = NULL;
	GtkIconInfo* i = NULL;
	GtkIconTheme* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	GtkIconInfo* _tmp5_ = NULL;
	GtkIconInfo* _tmp6_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = gtk_icon_theme_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	icon = _tmp1_;
	_tmp2_ = icon;
	_tmp3_ = name;
	_tmp4_ = size;
	_tmp5_ = gtk_icon_theme_lookup_icon (_tmp2_, _tmp3_, _tmp4_, GTK_ICON_LOOKUP_GENERIC_FALLBACK);
	i = _tmp5_;
	_tmp6_ = i;
	if (_tmp6_ != NULL) {
		GtkIconInfo* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp7_ = i;
		_tmp8_ = gtk_icon_info_get_filename (_tmp7_);
		_tmp9_ = g_strdup (_tmp8_);
		result = _tmp9_;
		_gtk_icon_info_free0 (i);
		_g_object_unref0 (icon);
		return result;
	} else {
		const gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		_tmp10_ = name;
		_tmp11_ = g_strdup (_tmp10_);
		result = _tmp11_;
		_gtk_icon_info_free0 (i);
		_g_object_unref0 (icon);
		return result;
	}
	_gtk_icon_info_free0 (i);
	_g_object_unref0 (icon);
}



